### ISSUE TITLE
Communication by running cfbridge.py is ok, but QGC can not detect CF2.

### ISSUE THREAD

**Issue by Xiaoyu0601-Wang** [bitcraze/crazyflie-lib-python#100]
The Crazyradio PA is connected with CF2 by running cfbridge.py. But QGC can not detect CF2 at the same time.
On the other hand, QGC can detect CF2 by running C based cfbridge.

Can anyone tell me which part I should modify?

Thank you.

**Comment by ataffanel** [comment]
If by QGC you mean 'QGroundControl' for PX4, the python bridge is not maintained by in this repos so you should post the ticket to the maintainer of the bridge.
