### ISSUE TITLE
Delays with many connections on one radio

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-lib-python#118]
In the ICRA demo we experience latency in out going packets when connecting more than 5 Crazyflies to one Crazyradio. When adding a second radio and moving 4 of the copter to it, the latency disappeared. 

The new radio used the same frequency (not recommended) so the number of useful packets in the air was probably reduced due to collisions, but performance was still better. The prime suspect for this problem is threading in python but more investigations are required.

**Comment by ataffanel** [comment]
The commit 1a5de7f should solve this issue. It has currently only been tested on connecting the 9 Crazyflies of the ICRA demo, not during operation. When connecting, it does seem to treat all connection fairly and all Crazyflies gets connected at the same time even if the full TOCs had to be fetched (it takes a lot of time to connect but it connects)

Lets close this ticket if we manage to run the demo with a single Crazyradio.
