### ISSUE TITLE
How to get the TDoA data in LPS?

### ISSUE THREAD

**Issue by Supredan** [bitcraze/crazyflie-lib-python#126]
Hi,

I want to get the TDoA data in LPS(Loco position system),and i found [lps-ros](https://github.com/bitcraze/lps-ros) which is exactly what i need .but unfortunately the output in the log_range is the data in the TWR mode, but in the LPS document,it is better to use the TDOA mode  to fly multiple drones, so I want to know how to get the TDOA data in ros,which is the different of distances between the two anchor.

Thank!

**Comment by krichardsson** [comment]
Please see [this answer in the forum](https://forum.bitcraze.io/viewtopic.php?f=3&t=3229&p=17780&hilit=tdoa+ros#p17780)

The log system is sampling the variable in the Crazylie and you will probably not get all TDoA data this way. The log system is unfortunately not really designed for this type of tasks. 

If you want all data it is possible to add a streaming protocol, [something similar to this](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/crtp_localization_service.c#L219
), but it requires some work in the firmware and modifications of the ROS driver. 

Other users have streamed TDoA data through a UART to another device, but then you will have a cable connected that will prevent flying :-)

**Comment by Supredan** [comment]
I will continue this topic in the forum, let us close him here
