### ISSUE TITLE
basicLedparamsync.py example doesn't work

### ISSUE THREAD

**Issue by dasmehdix** [bitcraze/crazyflie-lib-python#128]
Hi,
I can other examples without problem but `examples\basicLedparamsync.py` does not work.

The output  code writes:

> eriklab2@eriklab2-System-Product-Name:~/Desktop/crazyflie-lib-python/examples$ sudo python3 basicLedparamSync.py 
> Connecting to radio://0/80/250K
> Connected to radio://0/80/250K
> Traceback (most recent call last):
>   File "basicLedparamSync.py", line 69, in <module>
>     cf.param.set_value('ring.fadeColor', '0x0000A0')
>   File "/home/eriklab2/Desktop/crazyflie-lib-python/cflib/crazyflie/param.py", line 266, in set_value
>     raise KeyError('{} not in param TOC'.format(complete_name))
> KeyError: 'ring.fadeColor not in param TOC'

So I think problem is about parameters of the ring is wrong.How can I solve this issue?

**Comment by ataffanel** [comment]
This error could have two sources: the parameter does not exist or you are using a lib that is too old (for example installed long time ago with pip) and it does not support more than 256 parameters from the Crazyflie. I have verified and this parameter [still extists](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/deck/drivers/src/ledring12.c#L850).

Make sure you are using a recent version of both the Crazyflie firmware and the lib. You can make sure you are using the latest lib by installing it in edit mode with ```pip3 install -e .```. If you update your Crazyflie to version (2019.09)[https://github.com/bitcraze/crazyflie-release/releases/tag/2019.09]

I tested on my side and it works with both the latest lib and firmware so I am closing this ticket. Feel free to re-open if the problem persists.
