### ISSUE TITLE
Mellinger controller on Python

### ISSUE THREAD

**Issue by eduardo-del** [bitcraze/crazyflie-lib-python#149]
Hi guys

I have a problem when i try to run some example from cflib, when i try to run the position_commander_demo.py code my crazyflie just conneting with the crazyradio but the crazyflie dont run the task, just connected and after a little time it disconected, like if the crazyflie was finished his task.

On the firmware im using the mellinger controller.
In the moment just want to use the mellinger controller on Python, maybe after i will to use the mellinger controller on ROS.

Can someone help me?

thank you!!

**Comment by krichardsson** [comment]
This issue is duplicated in the forum https://forum.bitcraze.io/viewtopic.php?f=6&t=4276&p=19423&hilit=mellinger#p19423

Closing
