### ISSUE TITLE
Dongle communication error (ackStatus==None) when running from VirtualBox

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-lib-python#15]
Related to https://github.com/bitcraze/crazyradio-firmware/issues/28, when running the lib in virtualbox the USB communication sometime crash because reading the radio ack returns None. Since it does not seem to crash completely the communication there might be a way to ignore the communication error and continue communicating.

**Comment by evoggy** [comment]
When the radio ack returns None we used to call the link_error_callback which will disconnect the link and show the error message. After testing the case with the VM is seems as if getting Ack == None is ok and therefore the call to link_error_callback was removed and the connection stays up.
