### ISSUE TITLE
Sometimes the value of rssi average is nan

### ISSUE THREAD

**Issue by swarm5** [bitcraze/crazyflie-lib-python#161]
When I use radio-test.py, I often encounter error messages. I have changed a computer and it is still the same problem. **The value of rssi average is  nan.**
I ran the program three times in a row, only the second time it was correct. Errors occurred at channels 12 and 13 for the first and third time.Occasionally, most of the RSSI (~100) of the 125 channel is nan.
**Is crazyflie too far away from the radio? The distance between them is about 4m (2M communication frequency)**
**The same error message:**

> ('Channel', 12,'ack_rate:', 0,'rssi average:', 81.226415094339629,'rssi std:', 1.057614072244643)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
>   warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
>   arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)

**The results of the three experiments are as follows:**
1：
> ('Channel', 12, 'ack_rate:', 0, 'rssi average:', 78.876712328767127, 'rssi std:', 0.87499832452993487)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
>   warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
>   arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> ('Channel', 13, 'ack_rate:', 0, 'rssi average:', nan, 'rssi std:', nan)
> ('Channel', 14, 'ack_rate:', 0, 'rssi average:', nan, 'rssi std:', nan)
> ('Channel', 15, 'ack_rate:', 0, 'rssi average:', 71.631578947368425, 'rssi std:', 0.70416253475050783)
> ('Channel', 16, 'ack_rate:', 0, 'rssi average:', 69.011111111111106, 'rssi std:', 0.64108318830007349)
> ('Channel', 17, 'ack_rate:', 0, 'rssi average:', 67.326530612244895, 'rssi std:', 0.4689438895133084)
2：
> ('Channel', 11, 'ack_rate:', 1, 'rssi average:', 72.980000000000004, 'rssi std:', 0.52877216265609139)
> ('Channel', 12, 'ack_rate:', 0, 'rssi average:', 81.263157894736835, 'rssi std:', 0.90856192113852996)
> ('Channel', 13, 'ack_rate:', 0, 'rssi average:', 80.0, 'rssi std:', 0.81649658092772603)
> ('Channel', 14, 'ack_rate:', 0, 'rssi average:', 74.36363636363636, 'rssi std:', 0.64282434653322496)
> ('Channel', 15, 'ack_rate:', 0, 'rssi average:', 70.607594936708864, 'rssi std:', 0.70113328729753044)
3：
> ('Channel', 11, 'ack_rate:', 0, 'rssi average:', 72.711340206185568, 'rssi std:', 0.4965606011873111)
> ('Channel', 12, 'ack_rate:', 0, 'rssi average:', 81.226415094339629, 'rssi std:', 1.057614072244643)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
>   warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
>   arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
> /usr/lib/python2.7/dist-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> ('Channel', 13, 'ack_rate:', 0, 'rssi average:', nan, 'rssi std:', nan)
> ('Channel', 14, 'ack_rate:', 0, 'rssi average:', 76.0, 'rssi std:', 1.0)
> ('Channel', 15, 'ack_rate:', 0, 'rssi average:', 71.033333333333331, 'rssi std:', 0.65743609744386733)
> ('Channel', 16, 'ack_rate:', 0, 'rssi average:', 68.793103448275858, 'rssi std:', 0.62767461799889868)

**Comment by knmcguire** [comment]
closed due to inactivity. Sorry for the lack of answer for this... it's difficult to keep oversight. But I saw that crazyswarm was able to help to some extend.
