### ISSUE TITLE
logging variables over one block in size results in error

### ISSUE THREAD

**Issue by tomsoferRND** [bitcraze/crazyflie-lib-python#171]
recent [commit](https://github.com/bitcraze/crazyflie-lib-python/commit/b4a78fc2e306402b75d2053113b375b91b7c0b68#diff-8c3c67a2d6d9b29816572fd18013e7c76fb650c3adcd908d1edd3fcfd2de98c7) should allow me to add log variables more than one block in size and it should add blocks. 

using june 2020 firmware release. 

I modified examples/basiclog.py with these lines - to log 7 floats. (works with 6 floats)
any suggestions appreciated! thanks

`      self._lg_stab = LogConfig(name='Stabilizer', period_in_ms=500)
        self._lg_stab.add_variable('acc.x', 'float')
        self._lg_stab.add_variable('acc.y', 'float')
        self._lg_stab.add_variable('acc.z', 'float')
        self._lg_stab.add_variable('gyro.x', 'float')
        self._lg_stab.add_variable('gyro.y', 'float')
        self._lg_stab.add_variable('gyro.z', 'float')
        self._lg_stab.add_variable('gyro.xVariance', 'float')
`

the result was - 

INFO:cflib.crazyflie:Memories finished updating
DEBUG:cflib.crazyflie.toc:[2]: Using V2 protocol: 1
DEBUG:cflib.crazyflie.toc:[2]: Start fetching...
DEBUG:cflib.crazyflie:Adding callback on port [2] to [<bound method TocFetcher._new_packet_cb of <cflib.crazyflie.toc.TocFetcher object at 0x7f19453d5a90>>]
DEBUG:cflib.crazyflie.toc:[2]: Got TOC CRC, 217 items and crc=0x27C4BC76
INFO:cflib.crazyflie.toc:TOC for port [2] found in cache
DEBUG:cflib.crazyflie:Removing callback on port [2] to [<bound method TocFetcher._new_packet_cb of <cflib.crazyflie.toc.TocFetcher object at 0x7f19453d5a90>>]
DEBUG:cflib.crazyflie.toc:[2]: Done!
INFO:cflib.crazyflie:Param TOC finished updating
INFO:cflib.crazyflie:Callback->Connection setup finished [usb://0]
Connected to usb://0
DEBUG:cflib.crazyflie.log:Adding acc.x with id=105 and type=0x77
DEBUG:cflib.crazyflie.log:Adding acc.y with id=106 and type=0x77
DEBUG:cflib.crazyflie.log:Adding acc.z with id=107 and type=0x77
DEBUG:cflib.crazyflie.log:Adding gyro.x with id=133 and type=0x77
DEBUG:cflib.crazyflie.log:Adding gyro.y with id=134 and type=0x77
DEBUG:cflib.crazyflie.log:Adding gyro.z with id=135 and type=0x77
DEBUG:cflib.crazyflie.log:Adding gyro.xVariance with id=34 and type=0x77
DEBUG:cflib.crazyflie.log:Adding/appending log block id 1
DEBUG:cflib.crazyflie.log:First time block is started, add block
DEBUG:cflib.crazyflie.param:Requesting request to update param [0]
.
.
DEBUG:cflib.crazyflie.param:Requesting request to update param [216]
WARNING:cflib.crazyflie.log:Error 7 when adding id=1 (Block too large)
Error when logging Stabilizer: Block too large

**Comment by krichardsson** [comment]
Hi!

I see why #164 can be interpreted this way, but unfortunately this is not how it works. #164 is solving the problem when the **definition** of a log block requires more than one CRTP packet to be transfered to the Crazyflie. The size limit of a log block is still the same as the **log data** for one log block must fit in one CRTP packet when transmitted from the Crazyflie.

If you want to log more data you unfortunately still have to use multiple blocks (and the log data will be transmitted in multiple packets from the CF). There is a shortcut though when setting up the logging as you can pass in an array of log block definitions in the SyncLogger to make it easier.

```
with SyncCrazyflie('usb://0') as scf:
    with SyncLogger(scf, [block_def_1, block_def_2]) as logger:
            for log_entry in logger:
                # Use log data
```

**Comment by tomsoferRND** [comment]
thanks!
