### ISSUE TITLE
ValueError exception in /examples/qualisys/qualisys_hl_commander.py

### ISSUE THREAD

**Issue by mbaytas** [bitcraze/crazyflie-lib-python#185]
With Python 3.9 on Windows, line 116 `async for qtm_instance in qtm.Discover('0.0.0.0'):` raises the following exception and the script does not run:

    Exception has occurred: ValueError
    Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.
      File "C:\Users\baytas\Desktop\qualisys_hl_commander.py", line 116, in _discover
        async for qtm_instance in qtm.Discover('0.0.0.0'):
      File "C:\Users\baytas\Desktop\qualisys_hl_commander.py", line 101, in _connect
        qtm_instance = await self._discover()
      File "C:\Users\baytas\Desktop\qualisys_hl_commander.py", line 95, in _life_cycle
        await self._connect()
      File "C:\Users\baytas\Desktop\qualisys_hl_commander.py", line 92, in run
        asyncio.run(self._life_cycle())

**Comment by krichardsson** [comment]
As far as I understand this is a problem in the Qualisys lib https://github.com/qualisys/qualisys_python_sdk/issues/13

**Comment by mbaytas** [comment]
I was able to bypass the issue by modifying the `_connect` function:

    async def _connect(self):
            # qtm_instance = await self._discover()
            # host = qtm_instance.host
            host = "127.0.0.1"
