### ISSUE TITLE
Improve lighthouse support

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-lib-python#192]
In order to better support the lighthouse system from the lib, there needs to be more utility functions implemented to get and set geometry and calibrations data.

Lets use this ticket to groups commits that adds better support to the Lighthouse system.

**Comment by jonasdn** [comment]
When should this issue be considered _done_? Does anyone have a nice metric?

**Comment by whoenig** [comment]
I think we can close this once we released with Lighthouse support and removed the early-access tag from the webpage for the Lighthouse deck.
