### ISSUE TITLE
AMD64 missing on CPP link windows

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-lib-python#237]
The new CPP link doesn't install for the CFLib on windows. Currently line 13 of __init__.py in crtp is saying:

`if mach in ['x86_64']:`

and this should be

`if mach in ['AMD64']:`

Same goes for setup.py as well.

Currently if I do this change, the cfclient crashes if the crazyradio is inserted so probably we should wait for that fix before fixing this.

**Comment by jonasdn** [comment]
Nice catch! It should probably be:
```
if mach in ['AMD64', 'x86_64']:
```
