### ISSUE TITLE
potential issue with urihelper

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-lib-python#251]
Some reported instabilities for the URI helper. See this forum thread: https://forum.bitcraze.io/viewtopic.php?f=8&t=4952

**Comment by knmcguire** [comment]
@jonasdn have you had time to look at the forumpost and see if this is a problem or not?

**Comment by jonasdn** [comment]
> @jonasdn have you had time to look at the forumpost and see if this is a problem or not?

Yes, it was not a problem with urihelper, but rather with how the example was run.
