### ISSUE TITLE
Add P2P mode with relaxed CTRP timing

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-lib-python#257]
When connected to a Crazyflie, the lib will communicate as fast as possible with the Crazyflies. This means that there is no radio time left when using the P2P functionality implemented in bitcraze/crazyflie2-nrf-firmware#29 which prevents Crazyflie to talk to each-other the lib/client is connected to a Crazyflie.

One stop-gap solution, until we improve the radio link further, is to reduce the communication rate of the lib to free radio time for the P2P communication.

This could be done by adding one more optional parameter to the link: `radio://0/80/2M/E7E7E7e7E7?reduced_rate=10`. There is still at least 2 undecided questions:
 - What should the parameter name be?
 - Should the amount of bandwidth reduction be configurable?

**Comment by whoenig** [comment]
Would that simply reduce the ping-packets, or all packets? In the latter case, we would like need to implement it as a sleep in the radio thread between USB requests. If that's the case, we should make the sleep time configurable (and default to 0 for highest performance).

**Comment by ataffanel** [comment]
Yes, this is exactly what I am envisioning, optionally adding a sleep between USB/radio transfers. Any clue about a good name for it?

**Comment by whoenig** [comment]
what about `rate_limit`? This is better than `reduced_rate`, because it indicates that it is an upper limit, not the exact rate. The unit should probably be Hz.

**Comment by ataffanel** [comment]
> what about `rate_limit`? 

Sounds good! I pushed the change in a PR.
