### ISSUE TITLE
Dropping python 2.X?

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-lib-python#26]
The lib supports both python 2.X and 3.X while the client is python 3.X only. I'm suggesting to drop support for python 2.X for the lib as well to make the code cleaner and leaner. It would simplify maintenance and development as well as reduce complexity and risk. 

If there are a lot of users that run the lib with python 2.X it would obviously be a bad idea, so please let us know if you do!

**Comment by evoggy** [comment]
I would suggest keeping the compatibility. I think that a lib should be as compatible/usable as possible and the aim of the Python lib is not only to be used by the client. There's still lots of other libs that's interesting to use together with the Crazyflie but that only supports 2.7+ (like LeapMotion). When implementing the dual support constructs were selected that's supported in both 2.7+ and 3.4+ to minimize using if/else ([see this post](https://www.bitcraze.io/2015/09/moving-to-python-3/))

**Comment by IBISLabUMD** [comment]
The question of python2 compatibility is even more important 2 years later. 

Python2 support is being dropped officially on January 1, 2020. Many other packages, including potentially some that folks would use with the crazyflie i.e. numpy, are being dropped sooner. 

It is my belief that any libraries that do not support Python3 at this point indicate that they are outdated or not maintained. Supporting Python2 might be a small burden, but a burden nonetheless.

**Comment by krichardsson** [comment]
Thanks for your input!
We will not remove python 2 support for now, but will keep it in mind for the future

**Comment by krichardsson** [comment]
We have passed Jan 1 2020 when python 2 is no longer updated (https://www.python.org/doc/sunset-python-2/). We will remove python 2 support from the library.
