### ISSUE TITLE
Missing method in swarm example

### ISSUE THREAD

**Issue by s-mkokor** [bitcraze/crazyflie-lib-python#288]
When running the `hl-commander-swarm.py` example provided, I run in the issue that the method `reset_estimator` is not defined.
I use the official VM and executed the `Update all projects` scripts before I started.

I did some investigations and I think I know where the problem is:
Until some recent changes the method in question was part of the `hl-commander-swarm.py` example and then got moved to the lib. This was done after the Release 0.1.16. 

As far as I understand the `Update all projects` scripts loads the current master branch from github into the project folder and also reinstalls the latest version of the cflib. 

Therefore, the latest version of the `hl-commander-swarm.py` example is used, which is already missing the `reset_estimator` method. But on the same time version 0.1.16 of the cflib gets used which isn’t including the `reset_estimator` method yet.

this can be fixed easiyl manualy but still caused some confusion while getting started with the swarm example

**Comment by krichardsson** [comment]
Works in 2022.09, closing
