### ISSUE TITLE
Writing more the 112 bytes in 1-wire mem hangs cflib

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-lib-python#29]
While writing the erase function I accedentely was trying to erase 128 bytes to the 1-wire mem. This forces the lib into an endless retry loop because of status=5 (EIO). 

`Connected to usb://0
Found 1 1-wire memories
Erasing memory 2
INFO:cflib.crazyflie.mem:Writing new chunk of 25bytes at 0x0
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x0, status=0x0
INFO:cflib.crazyflie.mem:Writing new chunk of 25bytes at 0x19
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x19, status=0x0
INFO:cflib.crazyflie.mem:Writing new chunk of 25bytes at 0x32
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x32, status=0x0
INFO:cflib.crazyflie.mem:Writing new chunk of 25bytes at 0x4B
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x4B, status=0x0
INFO:cflib.crazyflie.mem:Writing new chunk of 25bytes at 0x64
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x64, status=0x5
INFO:cflib.crazyflie.mem:Status 5: write resending...
INFO:cflib.crazyflie.mem:Sending write again...
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x64, status=0x5
INFO:cflib.crazyflie.mem:Status 5: write resending...
INFO:cflib.crazyflie.mem:Sending write again...
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x64, status=0x5
INFO:cflib.crazyflie.mem:Status 5: write resending...
INFO:cflib.crazyflie.mem:Sending write again...
INFO:cflib.crazyflie.mem:WRITE: Mem=2, addr=0x64, status=0x5
INFO:cflib.crazyflie.mem:Status 5: write resending...
INFO:cflib.crazyflie.mem:Sending write again...
`

**Comment by ataffanel** [comment]
In case of EIO the function should fail and return the failure to the user of the lib.
