### ISSUE TITLE
Make debian packages

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-lib-python#3]
Now that the project follows pypa recomendation it should be easier to create a Debian package. This would help with installing the client on Ubuntu.

**Comment by kentwills** [comment]
@chriskuehl, I think this would be something you may be able to easily do if you are interested :)

**Comment by ataffanel** [comment]
We are pushing the project on pypi which means that it is installable with 'pip install cflib'. This should be good enough for distribution on all platform supported by python/pip. This makes a Debian package much less needed than before. I close this issue for now, if anyone is motivated about making a Debian package this issue can be re-opened.
