### ISSUE TITLE
Implement notifySetpointsStop packet

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-lib-python#301]
When switching from position setpoints to high level commander set points, it is necessary to implement the notifySetpointStop packet in the cflib api. 

see https://github.com/bitcraze/crazyflie-firmware/pull/903

**Comment by qubitter** [comment]
Maybe I don't understand, but what's the difference between notifySendpointStop and HighLevelCommander.stop()?

Doesn't really seem like we're doing much with setpoint in HighLevelCommander.

**Comment by knmcguire** [comment]
Hi! This is a functionality that exist in Crazyswarm and the firmware but not in the cflib. It is meant for better switching between regular setpoints and HL commands. So yes you are right, this is not a High level commander functionality.
