### ISSUE TITLE
python 3.12, can't compile due to missing packages

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-lib-python#425]
So, the cfilb package can not be installed on python 3.12 due to missing packages for that version. 

This was noticed as well in the client: https://github.com/bitcraze/crazyflie-clients-python/issues/687

We should mention this in the documentation.

**Comment by ataffanel** [comment]
This is already fixed.

**Comment by knmcguire** [comment]
Then we shouldn't forget to change this in the documentation

https://github.com/bitcraze/crazyflie-lib-python/blob/a77b4023867c27d814c6820373ec2a7d158a2ef5/docs/installation/install.md?plain=1#L8-L10
