### ISSUE TITLE
TOC Cache writing on swarm class hangs in thread

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-lib-python#468]
Sometimes in the swarm examples, the example hangs, in particular on the TOC cache writing which blocks all the other threads. 

This doesn't happen all the time, so we need to figure out how many times this happens, why and how to prevent it from happening (or at least say something useful and just exit). 

This needs to be investigated first before we can fix it (or not)

**Comment by gemenerik** [comment]
It does not hang with the recommended radio set-up #466
