### ISSUE TITLE
error when excute the basiclog example

### ISSUE THREAD

**Issue by cuongtv89ks** [bitcraze/crazyflie-lib-python#47]
I connected the crazyflie then run the example, but it has this error:
```

Scanning interfaces for Crazyflies...
Crazyflies found:
No Crazyflies found, cannot run example
Traceback (most recent call last):
  File "basiclog.py", line 143, in <module>
    while le.is_connected:
NameError: name 'le' is not defined


```
How to fix it?

thank in advance!!

**Comment by ataffanel** [comment]
Did you connect the Crazyflie or a Crazyradio? The examples will connect to the Crazyflie using the Crazyradio dongle.

**Comment by cuongtv89ks** [comment]
yes, I plugged Crazyradio dongle and connected to crazyflie but can not run example

**Comment by cuongtv89ks** [comment]
oh after restarting again, now it can connect :D

**Comment by ataffanel** [comment]
Good to read that the problem is solved. It might have been a problem with access right (after seting up the used rules file, the crazyradio has to be reconnected). I close the ticket.
