### ISSUE TITLE
Version incompatible with cfclient

### ISSUE THREAD

**Issue by simonjwright** [bitcraze/crazyflie-lib-python#52]
The version here is 0.1.2, but cfclient is looking for 0.1.3.

**Comment by ataffanel** [comment]
Thanks for reporting! This is a silly mistake: I forgot to push the commit updating to 0.1.3 (even though I pushed it on pypi) and then apparently tagged the wrong commit in github as being 0.1.3.

Unfortunately I do not see any way to solve the tag. But now if you pull master, it is at version 0.1.3
