### ISSUE TITLE
Multiramp question

### ISSUE THREAD

**Issue by RCYajad** [bitcraze/crazyflie-lib-python#67]
I have a thesis that needs to control four crazyflies simultaneously. I decided to use the multiramp code here. My question: is it possible to control four crazyflies using that code? Since I can successfully use the code to control two. Can I also use the code to have each crazyflie do their own thing?

**Comment by ataffanel** [comment]
Hi,
Yes, it will work with 4 just by duplicating the code that creates the MotorRampExample object: https://github.com/bitcraze/crazyflie-lib-python/blob/master/examples/multiramp.py#L113-L114
