### ISSUE TITLE
Data from terminal to a spreadsheet

### ISSUE THREAD

**Issue by jaycariaga** [bitcraze/crazyflie-lib-python#87]
So I have a code that merely has the crazyflie record accelerometer data during a hover and crash test run. I am wondering how to effectively transfer this recorded data to an excel spreadsheet. Although my code works and I do get results, I am just curious as to what is the optimal way of transferring data to excel.

**Comment by krichardsson** [comment]
If you are using a python script to record data, you could use the CSV module https://docs.python.org/3/library/csv.html to generate CSV data for instance that excel can read.

**Comment by ataffanel** [comment]
Closing since the solution solves your problem. Feel free to re-open if it does not.
