### ISSUE TITLE
Problem utilizing 'motorPowerSet' variables with a send_setpoint command

### ISSUE THREAD

**Issue by jaycariaga** [bitcraze/crazyflie-lib-python#88]
Hello there.
       I have been working on a python script that should turn off certain thrusters after turning on all of the thrusters for some time. I posted an attachment of my code and during execution, the crazyflie runs the whole 8 seconds without turning off the two thrusters as wanted. What is the best option to get the expected run to work? Is using the motorPowerSet variable the only possible way to alter a certain thruster?
       Oh, and the picture attachment is only a part of the code. Please let me know if you I need to show the whole code.
      
![image](https://user-images.githubusercontent.com/25041907/42770985-b64540a8-88f3-11e8-9052-e7be7bb79988.png)

**Comment by krichardsson** [comment]
Hi!

The code you supplied seems to work on my machine, not sure why you are having problems.

Note 1: This is a perfect question for the [forum](https://forum.bitcraze.io/). We try to use the forum for support and github for bugs and fatures

Note 2: A bitmap is not very useful for the people that you are asking for help, as they have to retype the code to try it out. Please copy/paste the code next time.
