### ISSUE TITLE
commander.py unit explanation  

### ISSUE THREAD

**Issue by mehmetyldz87** [bitcraze/crazyflie-lib-python#96]
" x and y are in m/s
 yaw is in degrees/s"

Are they right  or They should be "  m & degree " 

https://github.com/bitcraze/crazyflie-lib-python/blob/49fd8f636b137e505779069bef06b404863334d8/cflib/crazyflie/commander.py#L132

**Comment by ataffanel** [comment]
You are [right](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/crtp_commander_generic.c#L343-L368), this is a copy-paste mistake.
